import 'package:flutter/material.dart';
import 'package:keryx/core/identity/callsign.dart';
import 'package:keryx/core/theme/ux_tokens.dart';

import 'onboarding_copy.dart';
import 'onboarding_keys.dart';
import 'recovery_phrase_screen.dart';
import 'screenshot_guard.dart';

/// First-run flow: callsign entry → recovery phrase → [onDone].
///
/// Standalone: the shell (TASK-093) injects the 12 words and persistence
/// via [onDone]. This widget does not touch `lib/app_shell/**`.
///
/// [PopScope] blocks leaving the flow until the confirmation tap
/// (Design §2.6, V2-FR-002). System back on the phrase step returns to
/// callsign entry; it never skips the gate.
class OnboardingScreen extends StatefulWidget {
  const OnboardingScreen({
    super.key,
    required this.words,
    required this.onDone,
    this.initialCallsign = '',
    this.screenshotGuard,
  });

  /// 12-word phrase already generated by the caller (deterministic in tests).
  final List<String> words;

  /// Fired only after "I've written it down", with the validated callsign.
  final void Function(String callsign) onDone;

  final String initialCallsign;
  final ScreenshotGuard? screenshotGuard;

  @override
  State<OnboardingScreen> createState() => _OnboardingScreenState();
}

enum _OnboardingStep { callsign, phrase }

class _OnboardingScreenState extends State<OnboardingScreen> {
  _OnboardingStep _step = _OnboardingStep.callsign;
  late final TextEditingController _callsign = TextEditingController(
    text: widget.initialCallsign,
  );
  String? _callsignError;
  bool _confirmed = false;
  String _acceptedCallsign = '';

  @override
  void dispose() {
    _callsign.dispose();
    super.dispose();
  }

  void _continueFromCallsign() {
    try {
      final parsed = Callsign.parse(_callsign.text);
      setState(() {
        _callsignError = null;
        _acceptedCallsign = parsed.value;
        _step = _OnboardingStep.phrase;
      });
    } on FormatException catch (e) {
      setState(() => _callsignError = e.message);
    }
  }

  void _confirmPhrase() {
    _confirmed = true;
    widget.onDone(_acceptedCallsign);
  }

  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: _confirmed,
      onPopInvokedWithResult: (didPop, _) {
        if (didPop) return;
        if (_step == _OnboardingStep.phrase) {
          setState(() => _step = _OnboardingStep.callsign);
        }
      },
      child: _step == _OnboardingStep.callsign
          ? _CallsignStep(
              controller: _callsign,
              error: _callsignError,
              onContinue: _continueFromCallsign,
            )
          : RecoveryPhraseScreen(
              words: widget.words,
              screenshotGuard: widget.screenshotGuard,
              onBack: () => setState(() => _step = _OnboardingStep.callsign),
              onConfirmed: _confirmPhrase,
            ),
    );
  }
}

class _CallsignStep extends StatelessWidget {
  const _CallsignStep({
    required this.controller,
    required this.error,
    required this.onContinue,
  });

  final TextEditingController controller;
  final String? error;
  final VoidCallback onContinue;

  @override
  Widget build(BuildContext context) {
    final tokens = KeryxUxTokens.of(context);
    return Scaffold(
      key: OnboardingKeys.callsignScreen,
      backgroundColor: tokens.surfaceBase,
      appBar: AppBar(
        title: Text(
          OnboardingCopy.callsignTitle,
          style: KeryxUxTypography.screenTitle.copyWith(
            color: tokens.textPrimary,
          ),
        ),
        automaticallyImplyLeading: false,
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(KeryxUxSpacing.pageMargin),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Text(
                OnboardingCopy.callsignHint,
                style: KeryxUxTypography.body.copyWith(
                  color: tokens.textSecondary,
                ),
              ),
              const SizedBox(height: KeryxUxSpacing.cardSpacing),
              TextField(
                key: OnboardingKeys.callsignField,
                controller: controller,
                autofocus: true,
                textCapitalization: TextCapitalization.characters,
                maxLength: Callsign.maxLength,
                decoration: InputDecoration(
                  labelText: OnboardingCopy.callsignFieldLabel,
                  error: error == null
                      ? null
                      : Text(error!, key: OnboardingKeys.callsignError),
                ),
                onSubmitted: (_) => onContinue(),
              ),
              const Spacer(),
              SizedBox(
                height: KeryxUxSpacing.minTarget,
                child: FilledButton(
                  key: OnboardingKeys.continueButton,
                  onPressed: onContinue,
                  child: const Text(OnboardingCopy.continueLabel),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
