import 'package:flutter/material.dart';
import 'package:keryx/core/theme/ux_tokens.dart';

import 'onboarding_copy.dart';
import 'onboarding_keys.dart';
import 'recovery_phrase_grid.dart';
import 'screenshot_guard.dart';

/// First-run recovery-phrase step (Design §2.6, V2-FR-002).
///
/// [onConfirmed] is the only forward exit. Screenshot protection is
/// requested for the lifetime of this route via [screenshotGuard].
class RecoveryPhraseScreen extends StatefulWidget {
  const RecoveryPhraseScreen({
    super.key,
    required this.words,
    required this.onConfirmed,
    this.screenshotGuard,
    this.onBack,
  });

  /// Exactly 12 BIP-39 words, already generated by the caller.
  final List<String> words;

  /// V2-FR-002 confirmation. The only way this screen reports completion.
  final VoidCallback onConfirmed;

  /// Optional: return to callsign entry. Does not complete onboarding.
  final VoidCallback? onBack;

  final ScreenshotGuard? screenshotGuard;

  @override
  State<RecoveryPhraseScreen> createState() => _RecoveryPhraseScreenState();
}

class _RecoveryPhraseScreenState extends State<RecoveryPhraseScreen> {
  late final ScreenshotGuard _guard =
      widget.screenshotGuard ?? MethodChannelScreenshotGuard();

  @override
  void initState() {
    super.initState();
    _guard.setSecure(true);
  }

  @override
  void dispose() {
    _guard.setSecure(false);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final tokens = KeryxUxTokens.of(context);
    return Scaffold(
      key: OnboardingKeys.phraseScreen,
      backgroundColor: tokens.surfaceBase,
      appBar: AppBar(
        title: Text(
          OnboardingCopy.phraseTitle,
          style: KeryxUxTypography.screenTitle.copyWith(
            color: tokens.textPrimary,
          ),
        ),
        automaticallyImplyLeading: widget.onBack != null,
        leading: widget.onBack == null
            ? null
            : IconButton(
                tooltip: 'Back',
                onPressed: widget.onBack,
                icon: const Icon(Icons.arrow_back),
              ),
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(KeryxUxSpacing.pageMargin),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Expanded(
                child: SingleChildScrollView(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      Text(
                        OnboardingCopy.phraseBody,
                        key: OnboardingKeys.phraseBody,
                        style: KeryxUxTypography.body.copyWith(
                          color: tokens.textSecondary,
                        ),
                      ),
                      const SizedBox(height: KeryxUxSpacing.cardSpacing),
                      RecoveryPhraseGrid(words: widget.words),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: KeryxUxSpacing.controlGap),
              SizedBox(
                height: KeryxUxSpacing.minTarget,
                child: FilledButton(
                  key: OnboardingKeys.writtenDown,
                  onPressed: widget.onConfirmed,
                  child: const Text(OnboardingCopy.writtenDown),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
