#!/usr/bin/env python3
"""Generate matching gitignored .env files for local relay + token-svc.

Does not overwrite an existing .env unless --force is passed.
Secrets are CSPRNG hex; they never belong in git (relay/.gitignore,
token-svc/.gitignore already exclude .env).
"""

from __future__ import annotations

import argparse
import secrets
from pathlib import Path

RELAY = Path(__file__).resolve().parent.parent
TOKEN = RELAY.parent / "token-svc"


def _write(path: Path, body: str, force: bool) -> None:
    if path.exists() and not force:
        print(f"[gen_local_env] keep existing {path}")
        return
    path.write_text(body, encoding="utf-8")
    print(f"[gen_local_env] wrote {path}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true")
    parser.add_argument(
        "--external-ip",
        default="127.0.0.1",
        help="coturn external-ip (localhost cannot prove TURN against NAT)",
    )
    args = parser.parse_args()

    api_key = secrets.token_hex(16)
    api_secret = secrets.token_hex(32)
    turn_secret = secrets.token_hex(32)
    event_secret = secrets.token_hex(32)

    relay_env = f"""# Local-only. Gitignored. Generated by scripts/gen_local_env.py
DOMAIN=localhost
TURN_DOMAIN=localhost
ACME_EMAIL=dev@localhost
EXTERNAL_IP={args.external_ip}
LIVEKIT_API_KEY={api_key}
LIVEKIT_API_SECRET={api_secret}
TURN_SHARED_SECRET={turn_secret}
TURN_REALM=localhost
TOKEN_SVC_UPSTREAM=127.0.0.1:8080
LIVEKIT_RTC_PORT_START=50000
LIVEKIT_RTC_PORT_END=50200
COTURN_MIN_PORT=52000
COTURN_MAX_PORT=52999
"""
    token_env = f"""# Local-only. Gitignored. Keys MUST match relay/.env
LIVEKIT_API_KEY={api_key}
LIVEKIT_API_SECRET={api_secret}
EVENT_TOKEN_SECRET={event_secret}
TOKEN_TTL_SECONDS=300
RATE_LIMIT_MAX=30
RATE_LIMIT_WINDOW_SECONDS=60
RATE_LIMIT_TTL_SECONDS=3600
"""
    _write(RELAY / ".env", relay_env, args.force)
    _write(TOKEN / ".env", token_env, args.force)
    print("[gen_local_env] DOMAIN=localhost cannot obtain an ACME cert.")
    print("[gen_local_env] Start compose without caddy locally; use Caddyfile.local for /token.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
